name: simulation
services:
    ros-gazebo:
        stdin_open: true
        tty: true
        volumes:
            - ./volume:/root
            - ${SSH_AUTH_SOCK:-/dev/null}:/ssh-agent #this should allow you to push to github using your computers ssh keys
        container_name: g-ros
        environment:
            - DISPLAY=novnc:0.0
            - SSH_AUTH_SOCK=/ssh-agent
            - DOCKER_BUILDKIT=1
        build:
            # ssh:
            #     - default
            context: .
        depends_on:
            novnc:
                condition: service_healthy
        entrypoint: /entrypoint.sh
        command: bash

    novnc:
        stdin_open: true
        tty: true
        environment:
            - DISPLAY_WIDTH=1800
            - DISPLAY_HEIGHT=1050
            - NOVNC_RESIZE=remote
            - RUN_XTERM=no
        container_name: novnc
        ports:
            - 8080:8080
        image: theasp/novnc:latest
        healthcheck:
            test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
            start_period: 10s
            start_interval: 1.5s
            interval: 5m
            timeout: .5s
            retries: 3


volumes:
    volume:
        external: true
        name: volume